### ISSUE TITLE
DCO for governance repo

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#107]
TAC meeting discussion 5 MAY 2022: commits currently do not require signed-off-by, should we have a DCO process for the governance repo?  Does LF have a recommended one already?

**Comment by krtaylor** [comment]
DCO is not needed, covered by copyright under CC by 4.0. Copyright phrase to use in documents: 
"Copyright (c) contributors to the Confidential Computing Consortium. Licensed under CC-BY-4.0."
