### ISSUE TITLE
Apparent contradiction in terminology whitepaper

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#116]
Whitepaper says
> 4. confidential VM: a virtual machine that is executed inside a hardware-based TEE, whereby code and data within the entire VM image is protected from the hypervisor and the host operating system.

However the 5th column of the Full-Table.jpg seems to contradict that.  A "Confidential VM" is shown having a red boundary(in the TEE) which does not include the "entire VM image".  This contradiction is not explained.

**Comment by PenglinYang** [comment]
![image](https://user-images.githubusercontent.com/80935986/174204531-67ccb57f-023d-49a7-ba50-665b42f7a15c.png)

I used to draw this picture try to illustrate confidential process, confidential container and confidential VM. In my understanding, the two column left in confidential VM could move to the package model of confidential process

**Comment by dthaler** [comment]
Penglin's picture looks right to me (terminology aside).   I cannot open a pull request without having to completely redraw Eric's diagram since the source for the .jpg is not in the repository, I'm not sure what was used to generate it.  Hoping Eric can either do an update or share the source.

The "packaging model" row is a fine label, if the word "Confidential" is removed from each of the cells in that row.  I might add a separate row labeling which ones are CVM / CL / CP / CC / CVM.   Open to other ways to show the information but I personally think the definition section is right and the diagram should be updated to match.

**Comment by monavij** [comment]
But I think we should just drop confidential container definition. Containers are just a packaging mechanism. While process and VM are execution units and there are confidential compute technologies that can protect a process and a VM. Infact the way the confidential container definition is written there is no tech that can meet it. For native containers, you can only use SGX, but it  just runs the app process packaged inside the container in a TEE and not the container runtime, so does not meet the confidential container definition. For VT based containers they can run the whole container inside a TEE but its really inside a VM so is a confidential VM not confidential container. 

So my recommendation is that CCC drops confidential container definition and just keep confidential library, confidential process and confidential VM definitions.
