### ISSUE TITLE
Amend channel verbiage in Terminology paper

### ISSUE THREAD

**Issue by dcmiddle** [confidential-computing/governance#117]
in https://github.com/confidential-computing/governance/blob/main/terminology/common-terminology.md#package-deployability-prerequisites

Add text like "Attested Communication" in lieu of "Mutually Authenticated and Encrypted channel"

**Comment by dthaler** [comment]
@dcmiddle can you open a pull request?

**Comment by dthaler** [comment]
Discussion 14 July 2022:
Attestation is a covered in a separate bullet that is in addition to authentication and encryption.  No one else argued for a change, so accepting current consensus to keep as is.
