### ISSUE TITLE
Should we have any guidance on what Code of Conduct is acceptable

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#14]
Currently the proposed acceptance criteria just includes having "a" Code of Conduct.
Simon asked if it should be "an acceptable" Code of Conduct, which we could only say if we first had some requirements about whether a given code of conduct is "acceptable" or not.

In comparison, for licenses we can say that OSI-approved licenses are acceptable, but is there any criteria for codes of conduct?

**Comment by spjohnso** [comment]
What is LFs guidance?

On Feb 25, 2020 01:19, Dave Thaler <notifications@github.com> wrote:

Currently the proposed acceptance criteria just includes having "a" Code of Conduct.
Simon asked if it should be "an acceptable" Code of Conduct, which we could only say if we first had some requirements about whether a given code of conduct is "acceptable" or not.

In comparison, for licenses we can say that OSI-approved licenses are acceptable, but is there any criteria for codes of conduct?

**Comment by AevaOnline** [comment]
As far as I am aware, LF does not provide specific guidelines for their Projects. They do maintain a [CoC for LF Events](https://events.linuxfoundation.org/about/code-of-conduct/) which supersedes any project-specific CoC during a physical event which the LF operates.

Each body (CCC, CNCF, etc) may set their own guidelines, and projects within that body (eg, openenclave, enarx, etc) must follow the specific guidelines of that LF Project. For comparison, [CNCF projects default to the CNCF CoC](https://github.com/cncf/foundation/blob/master/code-of-conduct.md), but may make a request to the CNCF TOC to change that.

With that said, allow me to give some background on the CNCF situation. I'm also happy to go more in depth offline.

[Kubernetes currently references the CNCF CoC](https://github.com/kubernetes/community/blob/master/code-of-conduct.md), but we (the k8s CoC committee) have proposed to change it.

My recommendation is that the CCC adopt the[ Contributor Covenant v2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) as a baseline, and recommend all projects do the same. If projects wants to diverge, that should be allowed (and lightly discussed). I believe this process is light weight enough to get projects off the ground, and allow their unique cultures to evolve over time.

The most challenging part of CoC's is in handling incidents _transparently enough_ to maintain community cohesion and trust while dealing with difficult situations that, occasionally, involve the very leaders of that organization. To maintain this accountability to the community, Kubernetes has [established a CoC Committee](https://github.com/kubernetes/community/tree/master/committee-code-of-conduct) separate from the Kubernetes TOC. This is fairly "heavy weight" in terms of time and commitment, and I would not necessarily advise it in early stages of community formation.

**Comment by spjohnso** [comment]
Sounds like a GB issue rather than a TAC issue. I would suggest.

**Comment by jethrogb** [comment]
I think Contributor Covenant is a good baseline.

Are we going to reject potential member projects because they have their own CoC? i.e. force them to adopt a different CoC because they want to join CCC?

**Comment by spjohnso** [comment]
From what I can tell from public postings is that Intel's current policy is to recommend and promote the use of Contributor Covenant 1.4.

To answer Jethro's question, no I don't think you necessarily reject them because they have their own CoC, but some body within the CCC needs to be comfortable with the differences. I am guessing this will have to be part of the assessment that is made by the TAC in its recommendation for adoption to the board.

**Comment by spjohnso** [comment]
Update: Intel is working on updating its *official* policy on CoC to reference 2.0. In the meantime I think I will be happy with recommending 2.0 for CCC to the GB.

**Comment by lazaridiscom** [comment]
> Update: Intel is working on updating its _official_ policy on CoC to reference 2.0. In the meantime I think I will be happy with recommending 2.0 for CCC to the GB.

Very strange. Intel designs highly complex stuff. Without logic, it would fail.

Yet, Intel does  not use logic to assess "the concept of CoCs in general", and specific CoCs, like the CCC. They cannot withstand even a casual evaluation. 

Here is mine:

Be intelligent.
Be human.
Be you.

See, I stick to this, in that order. Still, I get discriminated within nearly every project.

See, no CoC protects an freethinking-individual against mainstream masses, they stick always together and hide behind their (misinterpretd, by majority vote) CoCs.

But then, me just a nobody.

.

P.S: Don't bother, I'll leave this project anyways, as I realized its under the Linux foundation. There was a time where Microsoft was the "tyrant". Nowadays its Linux & Co, an amateurish tyrant, far more dangerous.

**Comment by lazaridiscom** [comment]
Another related issue, a direct CoC violation, (me? Or the maintainers?)

https://github.com/openenclave/openenclave/issues/2638

A contributor suggest something, two(!) involved developers mess the essence completely up (ignoring the issue) and close.

Typical contributor would go away, with a scent of sadness.

**Comment by lazaridiscom** [comment]
There we go

https://github.com/openenclave/openenclave/issues/2638#issuecomment-595918810

**Comment by dthaler** [comment]
Addressed by PR #23
