### ISSUE TITLE
Progression Template: Projects should address security response

### ISSUE THREAD

**Issue by spjohnso** [confidential-computing/governance#16]
At F2F 2/27 discussion around Threat Research: Identified that projects should have a security response policy

Progression Template should identify what the security response policy is for a project.

This does open up the question about what's acceptable... and a standard template.

**Comment by spjohnso** [comment]
Should the security response change with the progression of the policy?

**Comment by dthaler** [comment]
https://github.com/openenclave/openenclave/issues/2675 is the issue I filed against the OE SDK on this same topic last week, and it's waiting for general TAC guidance.  Thanks Simon for filing this issue here to track.

**Comment by dthaler** [comment]
Discussion among the OE CGC was something along these lines might work:
1. Project documentation says to report security issues to a CCC security committee.
2. A security issue is later reported to the CCC security committee.
3. The CCC security committee informs any the project-specific security committee for any relevant projects.
4. The project forwards the report to any relevant organizations (e.g., _product_ representatives).

However, that would require guidance on requirements around who can be a "relevant organization".  E.g., besides cloud vendors, what about IoT vendors or other vendors using the project in a product? What if the product has only a tiny market share or set of users do they still qualify? What if the small market share is considered security critical (e.g., critical infrastructure)? What if someone asks "I use it in my own small business", is that sufficient to get on the list of embargoed disclosure recipients?   Hence TAC guidance to projects is requested.

**Comment by MikeCamel** [comment]
Enarx proposal here: https://github.com/enarx/rfcs/pull/19

**Comment by MikeCamel** [comment]
https://docs.openstack.org/project-team-guide/vulnerability-management.html - Openstack example.

**Comment by AevaOnline** [comment]
Thanks, Mike! You beat me to it :)

**Comment by dthaler** [comment]
TAC minutes from March 19 say:

1. We request that projects have a security response policy.
2. Details on an OE CGC group conversation are available here:
    https://github.com/confidential-computing/governance/issues/16 
3. There was some consensus around projects having their own security process and roll up issues to the CCC TAC as needed.
4. More conversation is required around
    1. Should we have a security committee and
    2. Should we have a security rep or advisor for projects and should that person be a member or simply a security consultant. More discussion is also required around embargos and embargo email lists (who gets the notice of the embargo / vulnerability).

**Comment by spjohnso** [comment]
Added requirement in https://github.com/confidential-computing/governance/pull/35

**Comment by dthaler** [comment]
> https://docs.openstack.org/project-team-guide/vulnerability-management.html - Openstack example.

That's a very helpful example.  I do note that it does not address all of the questions however.  

It says they "communicate it to a vetted group of stakeholders such as software distributions, deployers and service providers who may need extra time to have these fixes in place before the vulnerability becomes known to the general public".   But it is silent on how one applies to get into the "vetted group of stakeholders" and what the vetting process entails.  E.g., if you are a small deployer but have a high security clearance in some national jurisdiction, can you apply?  Would you be accepted?

**Comment by dthaler** [comment]
Here's a set of some questions that I think any particular security response policy should answer:

Inbound disclosure process:
1) How should a vulnerability be disclosed to the project?
2) Is anonymous disclosure permitted, and if so, how?

Outbound disclosure process:
3) Who gets early notice of embargoed vulnerabilities?   And is that list public or private?
4) How does one apply to get on the list of those who get early notice?
5) What is the process for vetting and approving such parties?  Are there any specific requirements that one must meet to get approved?

**Comment by dthaler** [comment]
Fixed in PR #56
