### ISSUE TITLE
Recommendations around mapping of "project" to github terminology

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#17]
https://github.com/confidential-computing/governance/blob/master/project-progression-policy.md has policies about how a "project" is submitted and evaluated.   When GitHub is used as the source code location, do we have any recommended (or required?) mapping to GitHub concepts.  Specifically:
a) Should the CCC project have its own GitHub organization, that can contain any number of repositories?   (Aeva convinced me to argue Yes to this question.)
b) Should the CCC project be a single GitHub repository?
c) Could it map to what GitHub calls a "project" (aka "project board") like at https://github.com/confidential-computing/governance/projects?  (I would argue probably no.)
d) Can the answer between vary by CCC project?

Once we have an agreed answer, we should make any corresponding clarifications in the project submission template and/or the Project Progression Policy document, as needed.

**Comment by AevaOnline** [comment]
Thanks for the summary, @dthaler. 

Based on my experience, a "project" very often necessitates multiple code repositories which are interrelated and may, or may not, be strictly interdependent. For example, the core code might live in one repo while separate hardware drivers live in their respective repos, and CI/CD automation may live in another repo.

Considering all of these repos to be part of one "project", and granting that project self-governing status, enables the contributor team to manage their own code organization as is most efficient for that "project"'s needs. I have not seen any benefit in the past from arbitrarily limiting each "project" to a fixed number of repositories.

Should a "project" abuse the privilege of CCC resources to create repos that appear to be unrelated to that project's mission, the CCC ought to have recourse to call this into question and discuss it with the "project" governing body.

I would anticipate that as a project moves "up" the project ladder, it may need to spawn more repos under the management of its community.

**Comment by lazaridiscom** [comment]
> c) Could it map to what GitHub calls a "project" (aka "project board")

Of course not. GitHub needs to correct this misnaming, e.g. rename "project board" to "board" or similar. 

That said, confidential-computing is far too high-tech to be kept back by two of todays major efficiency "killers", namely GitHub and the Linux Foundation.

Both entities need to evolve, need to fix their weaknesses and flaws.

I'm used to semiconductor-domain quality, and cannot understand why large companies settle with such low quality tool and organizational standards. Why do such companies adapt to nonsense, instead of ensuring that nonsense is fixed?

**Comment by lazaridiscom** [comment]
To express this more technically:

## Actions

### Issue Boards

=> Ask github to rename the "Project Boards" to "Issue Boards" (short "Boards").

### Parent Organization

=> Ask github to provide a solution for the given organizational problem.

Larger Organizations have far too many projects under one account. "Hierarchy" is needed.

Linux Foundation => Confidential Computing => OpenEnclave => repos

Another example: https://github.com/microsoft (3k reposs, zero hierarchy)

(to my knowledge, there is no official github-related issue-tracker available)

**Comment by MikeCamel** [comment]
Enarx has https://github.io/enarx and sub-repos.

**Comment by dthaler** [comment]
Related question: if a "CCC Project" maps to a "GitHub org" then is there any CCC process needed around adding repos into the same org?  (I'm guessing no in general.)   What if the new repos expand the scope of the "CCC Project"?   Might be related to the Annual Project Reviews issue #18, i.e., maybe no process other than Annual Project Review checking that the answers in the submission template are still correct or need to be changed.  Although I think projects could be encouraged to proactively inform the TAC when something changes that affects their submission template (e.g., changing a License, or changing the security reporting process, or whatever else the TAC cares about in the template).

**Comment by dthaler** [comment]
From April 16 TAC meeting minutes:
* Projects may contain multiple repos, so how do we treat sub-repos or subprojects of a project we want to accept.
* The TAC should do an “annual review” of projects. One of the things we should
do is to check if there are any deltas from the original accepted project.
* Projects should proactively notify the TAC when they make substantial changes
to their project.
* If we keep a project review lightweight, it would allow us to have “minimum viable
governance”, where this review could grow organically with our projects / the
Consortium.
* We will begin to work on what the text for this will be as there is no pull request
today.
