### ISSUE TITLE
Project "charters"?

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#19]
The Project Progression Policy document says:

> The proposal document will be finalized and a project charter prepared. This charter document must be included in the project's main repository.

What is the project "charter"?  Who creates it, the TAC or the project's own governance? And who is authoritative for its contents?   Is there a charter template, or any examples of such a "charter" to point to?

**Comment by dthaler** [comment]
From the April 16 TAC meeting minutes:
* We are reaching out to Scott (Linux Foundation) to find the history of the Project
Charter Document which was originally provided to the CCC.
* We need to document a flow diagram for onboarding a project and we want to
know where the technical charter fits into that.
* This issue is assigned to Stephen Walli and he will follow up with the TAC if this
is not a purely legal / governing board issue

**Comment by spjohnso** [comment]
As part of #46 I moved the charter requirement line out of a TAC section and into a final section that the GB issued the charter and it had to be displayed.

**Comment by stephenrwalli** [comment]
I believe this should be closed. @cetola Please ensure the web design work includes a link on a per project basis for the PDF of the individual project charters to be linked.

**Comment by dthaler** [comment]
There should be a "Close issue" button for anyone with permissions to close.   However, I would recommend not closing it until any fix is merged.  For example, the issue asks "Is there a charter template?" and I haven't seen an answer to that question yet.  Is there one?

**Comment by stephenrwalli** [comment]
Fair comment re: ensuring template (blank) is available and the current charters are published.

**Comment by dthaler** [comment]
Stephen posted the template to the list which is: https://lists.confidentialcomputing.io/g/main/files/Governing%20Board/Docs/LF_Projects_Technical_Charter.pdf

But the current charters are still not published.

**Comment by cetola** [comment]
As an update, the CCC Charter and Technical Charter Template (provided by the LF) are located here:
https://lists.confidentialcomputing.io/g/main/files/Governing%20Board/CCC%20Charter

I will add completed technical project charters here:
https://lists.confidentialcomputing.io/g/main/files/Governing%20Board/Project%20Charters

Currently OE SDK and Enarx are up there. I'll work on getting the others posted as well.
