### ISSUE TITLE
Veraison project materials need to be posted

### ISSUE THREAD

**Issue by dcmiddle** [confidential-computing/governance#191]
We had incomplete tracking of project materials.
https://github.com/confidential-computing/governance/pull/190 consolidates the location.
The Veraison charter is there but not the submission document. 
Please add that.
Please also add a Gramine section to Projects/README.md (noting the new path if #190 is accepted).

**Comment by thomas-fossati** [comment]
> [...] The Veraison charter is there but not the submission document. Please add that.

hi @dcmiddle, is [this](https://github.com/veraison/community/blob/main/CCC/veraison-ccc-project-veraison-proposal.pdf) the missing document?

If so, I'll add it once #190 is merged.

If not, could you enlighten me on what document is needed? :-)

**Comment by dcmiddle** [comment]
> > [...] The Veraison charter is there but not the submission document. Please add that.
> 
> hi @dcmiddle, is [this](https://github.com/veraison/community/blob/main/CCC/veraison-ccc-project-veraison-proposal.pdf) the missing document?

That's it - thanks for the quick response!

**Comment by thomas-fossati** [comment]
> > > [...] The Veraison charter is there but not the submission document. Please add that.
> > 
> > 
> > hi @dcmiddle, is [this](https://github.com/veraison/community/blob/main/CCC/veraison-ccc-project-veraison-proposal.pdf) the missing document?
> 
> That's it - thanks for the quick response!

Cool, thanks for confirming!
