### ISSUE TITLE
Certifier Framework Project Proposal

### ISSUE THREAD

**Issue by bensternthal** [confidential-computing/governance#202]
### Project Documentation & Links

https://github.com/vmware-research/certifier-framework-for-confidential-computing/

### Project Checklist

- [X] TAC [Vote](https://github.com/confidential-computing/governance/blob/main/TAC/Meetings/2023/2023-10-19/TAC%20Minutes%202023-10-19.md) 
- [X] Technical Charter Draft Reviewed By Legal
- [x] Contribution Agreement Not Needed
- [x] Board Vote
- [x] Add ‘thelinuxfoundation’ as an owner of the GitHub org
- [x] Transfer any domains
- [ ] Onboard to LFX
- [x] Add docs to [repo](https://github.com/confidential-computing/governance/tree/main/Projects) https://github.com/confidential-computing/governance/pull/220
- [x] Add to website

**Comment by bensternthal** [comment]
Waiting on github repo change so that we can skip the contribution agreement.

**Comment by bensternthal** [comment]
Neutral org created https://github.com/ccc-certifier-framework

Waiting on admin from vmware/broadcom with permissions to move the existing repository.

**Comment by bensternthal** [comment]
Repo has been moved to neutral org. We will aim for a board vote on Jan 17.

**Comment by bensternthal** [comment]
Waiting on LF to stand up the Series LLC for Certifier Framework.

**Comment by bensternthal** [comment]
Final docs received, we are now able to add to github and the website.

**Comment by Riaankl** [comment]
Added Certifier Framework Project to the CCC website and [requested update](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-24389) of project category in PCC to incubation under Apache License 2.0
