### ISSUE TITLE
 VirTEE Project Proposal

### ISSUE THREAD

**Issue by bensternthal** [confidential-computing/governance#203]
### Project Documentation & Links

https://github.com/virtee

### Project Checklist

- [X] TAC Vote https://github.com/confidential-computing/governance/blob/main/TAC/Meetings/2023/2023-06-01/CCC-TAC-Minutes-2023-06-01.md
- [x] Technical Charter Draft Reviewed By Legal 
- [x] Contribution Agreement Signed 
- [x] Board Vote / Make Active
- [x] Add ‘thelinuxfoundation’ as an owner of the GitHub org  (⚠️ verify)
- [x] Transfer any domains  
- [X] Onboard to LFX
- [x] Add docs to [repo](https://github.com/confidential-computing/governance/tree/main/Projects) https://github.com/confidential-computing/governance/pull/216

**Comment by dcmiddle** [comment]
we also need the docs into https://github.com/confidential-computing/governance/tree/main/Projects

**Comment by bensternthal** [comment]
Yep noted, also note I requested the final technical charter from the project formation team.

**Comment by bensternthal** [comment]
Board vote on Jan 17.
