### ISSUE TITLE
ManaTEE  - PrivacyGo Data Clean Room Project Proposal

### ISSUE THREAD

**Issue by riaankleinhans** [confidential-computing/governance#247]
## Project Documentation & Links

Project Name: PrivacyGo Data Clean Room
Project Repository: https://github.com/vinijaiswal/privacygo-datacleanroom-donation/ https://github.com/tiktok-privacy-innovation/PrivacyGo-DataCleanRoom
Project Proposal:  [Data Clean Room Project - CCC.pdf](https://github.com/user-attachments/files/16381750/Data.Clean.Room.Project.-.CCC.pdf)

### Project Checklist

- [X] TAC Vote (Date: **2024-07-25**)
- [x] New Project Created In LFX
- [x] Project Submission [Form Submitted ](https://docs.google.com/forms/d/e/1FAIpQLSeO1bDGHUP-ZpCo1uynm94YOxZlek6RhCH7o3FnX1lZSXXfSQ/viewform?fbzx=4351560609072672295)
- [x] Technical Charter / Participation Agreement / Trademark docs approved & signed by project
- [x] Board Vote (Date: )
- [x] Project made active in PCC by notifying the formation team
- [x] Create a support ticket to add the project category (Incubating / Graduated) and software license to project the definition
- [x] Add ‘thelinuxfoundation’ as an owner of the GitHub org
- [x] Transfer any domains
- [x] LFX: Add To Insights
- [x] Update website
- [x] Add docs to [repo](https://github.com/confidential-computing/governance/tree/main/Projects)
- [x] Add to [project tracker](https://docs.google.com/spreadsheets/d/1crFOI5KRiYwZpurHuXdN7NnNVjCVddg2GKhVD72STIY/edit#gid=0)

**Comment by riaankleinhans** [comment]
Documents received from Project formation team and shared with Vini for review. July 31

**Comment by riaankleinhans** [comment]
Project requested to change their name to ManaTEE. Sent the request through to the formation team.

**Comment by dcmiddle** [comment]
That's a great name!

**Comment by riaankleinhans** [comment]
Can you imagine the logo @dcmiddle ?

**Comment by riaankleinhans** [comment]
Further request received trademark and IP risk for both ManaTEE & OpenTRE

**Comment by riaankleinhans** [comment]
All updates are done!
