### ISSUE TITLE
Clarify terminology: Mentorship of CCC projects and Mentorship program for work in CCC Projects.

### ISSUE THREAD

**Issue by riaankleinhans** [confidential-computing/governance#249]
Currently, the term "mentor" refers to both [Project Mentors](https://github.com/confidential-computing/governance/blob/main/project-mentors.md), who sponsor and champion projects within the CCC, and mentors in the [CCC mentorship program](https://github.com/confidential-computing/governance/tree/main/mentoring), who work directly with mentees on CCC projects.

To avoid confusion between these two distinct roles, we propose changing the term "Project Mentor" to "Project Liaison." This change more accurately reflects the role of these individuals in supporting CCC projects.

A pull request will be created to implement this change.

**Comment by dcmiddle** [comment]
I think this is a helpful change to resolve a frequent point of confusion.
CCC TAC members have `Liaison` roles with our projects.
Our Project maintainers supported by TAC funding offer `Mentorships` to new contributors.

**Comment by dcmiddle** [comment]
cc: @confidential-computing/tac-voting-members

**Comment by yashkmankad** [comment]
Agreed.
Thanks @riaankleinhans  and @dcmiddle !

**Comment by fritzalder** [comment]
I agree, the new name is also more fitting. Thanks!

**Comment by AlecFernandez** [comment]
Thaks for the callout and suggestion @riaankleinhans. Agreed that Liason is a clearer term
