### ISSUE TITLE
Committee charters

### ISSUE THREAD

**Issue by AevaOnline** [confidential-computing/governance#28]
Should we capture, in the project documentation, the charter and scope of each of the committees? 

While I believe I now know what Outreach, TAC, and GB do, it may be helpful to communicate the breakdown of responsibilities through a document we can point others to.

**Comment by dthaler** [comment]
I think so yes, and I think this item should be assigned to the Board (as opposed to the TAC).  To my knowledge, only the TAC has content in GitHub so far so this repo is currently the best/only place to track this issue in GitHub.

**Comment by dthaler** [comment]
At was pointed out in the board meeting that on the website https://confidential-computing.io the charter is available via About->Charter which talks about the committees

**Comment by stephenrwalli** [comment]
I want to echo @dthaler's observation. This is in the charter. I do not want to create competing bodies of text in different places. Is there a place @aeva would suggest a PR that makes it obvious to go read the charter link for more detailed discussions?

**Comment by spjohnso** [comment]
In the overview PDF there are two pages on the Consortia structure & the FAQ has a link to the charter in "how is the consortia governed?" question.

**Comment by dcmiddle** [comment]
It appears from the comments here that this issue is resolved. i.e., the Charter text covers this.
