### ISSUE TITLE
Project Progression Policy document should point to submission template

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#3]
The "Project Proposal Requirements" section contains a list of required information in a submission.  It should have a link to the submission template, and state how to do the actual submission.

**Comment by dthaler** [comment]
Template (including how to do the actual submission) is currently at
https://lists.confidentialcomputing.io/g/tac/wiki/Project-Proposal-Template

**Comment by dthaler** [comment]
There are also currently some apparently contradictions between the Project Progression Policy document and the Project Proposal Template, e.g., logo is an item on the template but not in https://github.com/confidential-computing/governance/blob/master/project-progression-policy.md#project-proposal-requirements.   I'd suggest we remove the "Project Proposal Requirements" from the policy document and replace them with a link to the template, so the requirements are in only one document.

**Comment by spjohnso** [comment]
should we have a copy of the progression template also in the repo? If this is the way we're going to maintain and comment on docs

**Comment by dthaler** [comment]
> should we have a copy of the progression template also in the repo? If this is the way we're going to maintain and comment on docs

I agree, moving the template to GitHub rather than a wiki is a great idea.

**Comment by cetola** [comment]
Resolved here:
https://github.com/confidential-computing/governance/commit/bd1f4a0a29cbfc24b7c1d6a39aafb75907394178
