### ISSUE TITLE
"TBD Document" for where projects can learn about Consortium benefits

### ISSUE THREAD

**Issue by annabellegoth2boss** [confidential-computing/governance#32]
Under the [Project Progression Policy](https://github.com/confidential-computing/governance/blob/master/project-progression-policy.md), last sentence in Overview has a "TBD Document" link for where projects can learn the benefits of donating to the Consortium. 

This ties into the larger work @aevaonline and I have been doing around Outreach Committee support of projects, so this issue can be attached to that work.

**Comment by dthaler** [comment]
The sentence is: "For more information about how your project can benefit from Consortium membership and services, please see TBD Document."

Maybe "membership" is a bad word there if one does not need to join the consortium to contribute a project?

**Comment by annabellebertooch** [comment]
Agree; I don't think this doc is about CCC Membership, but is, "I've donated my project, what kind of services and support can my project expect (per its project level)"
