### ISSUE TITLE
Are there other categories of projects we want

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#34]
Question from previous TAC discussion was about other types of projects we want to attract, and what we might do to get them

**Comment by dthaler** [comment]
@spjohnso  This issue is to track the action item you are working on

**Comment by spjohnso** [comment]
[2020 WW12 CCC UseCase & Project Analysis v2.pdf](https://github.com/confidential-computing/governance/files/4430447/2020.WW12.CCC.UseCase.Project.Analysis.v2.pdf)

Here is an annotated copy of the presentation we gave at the TAC F2F 4/2/2020 original file is in the meeting minutes [PPT](https://lists.confidentialcomputing.io/g/main/files/TAC/Meetings/2020/CCC%20TAC%20Agenda%202020-04-02%20-%20projects%20discussion.pptx)
and [PDF] (https://lists.confidentialcomputing.io/g/main/files/TAC/Meetings/2020/CCC%20TAC%20Agenda%202020-04-02%20-%20projects%20discussion.pdf)

**Comment by dthaler** [comment]
Not sure if there are any conclusions or next steps?  @spjohnso What needs to happen before closing this issue?

**Comment by spjohnso** [comment]
We were already going to have the outreach write a set of use cases. Do we want to provide a more formal write up of the project analysis or is the PDF sufficient. Is there any interest beyond what we've done so far.? what would we do with such documentation?

**Comment by dthaler** [comment]
Closing per TAC meeting discussion
