### ISSUE TITLE
What if a project wants to spin-off a library as sub-project?

### ISSUE THREAD

**Issue by spjohnso** [confidential-computing/governance#36]
Do we need any specific process for spinning-out a sub-project from an already approved project? Or does it become just another a second project under the auspices of previously approved project?

**Comment by dthaler** [comment]
This issue may be related to issue #17

**Comment by dcmiddle** [comment]
Per #17 projects should use whatever code and repo organization that makes sense to them for code within their charter. 
Should a project want to separately operate a library or other offshoot of their original charter that should be a new project submission.
Reasons to spin-out a new project may include that the scope, governance, or participants are distinctly different than the original project charter, and not merely a reorganization of code or minor expansion of scope.

**Comment by spjohnso** [comment]
[Proposal in TAC call 4/30](https://lists.confidentialcomputing.io/g/main/files/TAC/Meetings/2020/04-Apr/CCC%20TAC%20Agenda%202020-04-30.pptx) was offered by TAC Chair.

* CCC project can have any number of repos under same github org (if using github)
* If intent is to still be part of same CCC project as far as website, etc goes:
  * No specific process, project can just move code to another repo under same github org
* Else if intent is to be viewed as a separate (new) CCC project:
  *Would need to go through TAC review as any other new project would

**Comment by dthaler** [comment]
Closing issue now that PR #49 is merged.
