### ISSUE TITLE
CoC: Contact address needs updating

### ISSUE THREAD

**Issue by spjohnso** [confidential-computing/governance#37]
[CoC](https://github.com/confidential-computing/governance/blob/master/code-of-conduct.md) uses legal@confidentialcomputing.io as it's contact address for reporting issues.

I believe we agree in the TAC (although I cannot find a reference in the minutes) to address this to separate contact list.

**Comment by spjohnso** [comment]
It was an action in the Governing Board. conduct@confidentialcomputing.io is the address that was created.

**Comment by dcmiddle** [comment]
resolved a long time ago but never closed.
