### ISSUE TITLE
Project Progression Policy: requirement for 2 mentors

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#4]
Current policy says even for sandbox stage:
"To be considered for the Sandbox Stage, the project must meet the following requirements:
2 TAC representatives that will serve as sponsors to champion the project & provide mentorship as needed"

However, TAC discussion so far has been, I believe, that only 1 is required for now at this stage.

**Comment by dthaler** [comment]
TAC suggestion to change to 1 sponsor for now

**Comment by cetola** [comment]
Resolved here:
https://github.com/confidential-computing/governance/commit/edbbba4ad05f2962e05afb6b72eb35a031c50fcc
