### ISSUE TITLE
Update the CCC Charter per the Governing Board vote in September

### ISSUE THREAD

**Issue by cetola** [confidential-computing/governance#67]
See here:
https://lists.confidentialcomputing.io/g/governingboard/topic/76621014

The charter should be updated and posted on the website:
https://confidentialcomputing.io/ccc_charter/

**Comment by dthaler** [comment]
@cetola can this issue be closed now?

**Comment by cetola** [comment]
Yes, big thank you to @ashleyweltz for getting this done.

Latest charter is here:
https://confidentialcomputing.io/wp-content/uploads/sites/85/2021/05/Confidential-Computing-Consortium-Charter.pdf
