### ISSUE TITLE
Progression Template: Add requirement for description of TCB

### ISSUE THREAD

**Issue by spjohnso** [confidential-computing/governance#7]
At the 1/23/2020 TAC meeting decided to add a requirement for projects to describe their TCB.

**Comment by spjohnso** [comment]
Here is my proposal:
Add the following to the list of items in the template.

* Describe the the TCB of the project. if the project supports multiple environments please describe each TCB. Also identify if dependencies of other project (both CCC or non-CCC) TCBs are taken.

**Comment by cetola** [comment]
@spjohnso please send me a pull request with that fix and I will merge it.

**Comment by cetola** [comment]
Resolved here:
https://github.com/confidential-computing/governance/commit/8d188db4d6381962aa69c808b80354e00c5084af
