### ISSUE TITLE
Proposal: the CCC should work with the Linux kernel community to agree on the host-to-guest threat model and attack mitigation for confidential guests

### ISSUE THREAD

**Issue by tmroeder** [confidential-computing/governance#71]
# Problem

Confidential-computing architectures like AMD SEV-SNP and Intel TDX assume a threat model that admits _host-to-guest_ attacks, in which a host component (host/dom0 kernel, hypervisor, or devices) may perform arbitrary operations to attempt to compromise the confidentiality or integrity of guest operations and memory<sup>1</sup>. The Linux kernel threat model for guests usually excludes host-to-guest attacks, since guest kernels before confidential computing needed to trust their host components. The host-to-guest attack surface in the guest kernel is large and includes shared buffers, I/O, assigned devices, and even hypervisor return values. Confidential guests can no longer trust these values and must validate them before consumption.

For example, Linux leaves DMA memory unencrypted so that devices can still communicate directly with guest kernels. This choice additionally leaves DMA memory readable to and modifiable by malicious hypervisors, which can modify control structures, DMA addresses, and other information stored in DMA memory; these kinds of data are regularly stored by device drivers in DMA memory for performance reasons.

Host-to-guest vulnerabilities [currently exist in upstream Linux](https://www.spinics.net/lists/kernel/msg3743483.html), but guests are not vulnerable outside the confidential-computing threat model. Google's Virtualization Security Team has examined the NVMe and gVNIC drivers in upstream Linux and found cases where, for example, DMA addresses are stored in DMA memory and are later trusted by the NVMe driver and passed to DMA deallocation. A malicious hypervisor could change these addresses to cause the NVMe driver to deallocate arbitrary pages in the Linux kernel.
 
Left unfixed, these vulnerabilities vitiate the promise of confidential computing by introducing new attack vectors on supposedly more secure systems.

# Proposal

Finding and fixing host-to-guest vulnerabilities will require the support of the Linux kernel community. Gaining that support will require broad discussion and agreement on LKML about the confidential-computing threat model, the class of attacks, and methods to mitigate them. As the organization representing companies that want to use confidential computing, the Confidential Computing Consortium should open and lead this conversation with the Linux kernel community.

<hr/>
<sup>1</sup> These architectures cannot guarantee availability because the hypervisor controls guest scheduling.

CC: @dthaler, @dfrenkel

**Comment by jethrogb** [comment]
Specifically for DMA-related issues, isn't the CC threat model very similar to a threat model that includes malicious peripheral (see various rDMA attacks)?

**Comment by tmroeder** [comment]
> Specifically for DMA-related issues, isn't the CC threat model very similar to a threat model that includes malicious peripherals (see various rDMA attacks)?

Yes, I think so.

One small difference in this case is that the hypervisor can (currently) pretend to have peripherals that aren't really there and cause the kernel to load drivers that it wouldn't otherwise have loaded. That means that any driver that uses DMA can put the kernel at risk as opposed to just the drivers for the devices that happen to be present.

**Comment by gregkh** [comment]
nit, can you point to lore.kernel.org for upstream kernel mailing list discussions, other mailing list archives do not always work properly and do not allow for adding to the discussion directly like lore does.

**Comment by gregkh** [comment]
Also, patches for these perceived issues are the best place to start with, "discussions" do not work as everyone likes talking but nothing matters if you do not have a proposed solution that you wish to see merged.

**Comment by hansendc** [comment]
Seconding what Greg said...  You don't need to get a bunch of companies together in advance to fix an issue in the kernel.  I'd suggest finding a *simple* host->guest attack vector that exists today and could impact real SEV/TDX users and post a patch for it.  Any discussion about whether this is a good idea will happen as a result of that patch.

Feel free to cc me (dave.hansen@intel.com) on any such patch submission.  I'll be happy to chime in.

**Comment by tmroeder** [comment]
Thanks, everyone, for the valuable feedback. As it happens, I'm going to be switching to a different part of Google internally, and I'm not going to be working on this problem anymore, but I've been talking to colleagues about continuing along the lines suggested: finding a simple instance of this problem and sending a patch. I hope that they will be able to move this work forward (but of course, I can't make any guarantees on behalf of Google, etc.).
