### ISSUE TITLE
Template needs link to Consortium's Mission Statement

### ISSUE THREAD

**Issue by dthaler** [confidential-computing/governance#9]
https://github.com/confidential-computing/governance/blob/master/project-progression-template.md has:
`How` does this project align with the Consortium's Mission Statement

But the feedback was that this cannot be answered without knowing what that mission statement is, so the template needs this requirement to be linked to the actual mission statement

**Comment by cetola** [comment]
Resolved by commit f29bd6f915831927da5b9441c37ff0758eadc221
